/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "id",
    "aws_user_pools_web_client_id": "anotherid",
    "oauth": {
        "domain": "yourdomain.auth.us-east-2.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile"
        ],
        "redirectSignIn": "http://localhost:4200/login",
        "redirectSignOut": "http://localhost:4200/home",
        "responseType": "token" // token | code (Error: Cannot retrieve a new session. Please authenticate.)
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "awsomeblog-tenant1-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://subdomain.cloudfront.net"
};

export default awsmobile;